### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by javadba** [dwt/fluent#5]
Last official release was twelve months back - and you have done quite a bit of work since then.  While I can `git clone` and install locally it would be helpful to have a `pip install` able  for distributions.

**Comment by dwt** [comment]
Though, it will probably have to be a major version, as it contains some breaking changes. (I have changed some return types, for example, `Iterable.iter()` now returns unwrapped objects.

**Comment by dwt** [comment]
I have a first version of the documentation online at https://fluentpy.readthedocs.io/en/latest/?badge=latest (in preparation of a new release).

Would you mind taking a look?

**Comment by dwt** [comment]
I have also started putting up more example code of how to use fluentpy here: https://github.com/dwt/fluent/blob/master/examples/aoc2018/fluentpy.ipynb

I'd love to hear if that provides better examples (I think you said once that you are missing better/ more example code).

**Comment by dwt** [comment]
And here's a prerelease of what I intent to publish - I'd love if you could give this a go around. :-)

https://pypi.org/project/fluentpy/2.0b1/

**Comment by javadba** [comment]
Using this now
Requirement already satisfied: fluentpy in ./Library/Python/3.7/lib/python/site-packages (1.0.1)

**Comment by dwt** [comment]
https://pypi.org/project/fluentpy/

:-)

**Comment by dwt** [comment]
Oh, and I'd love some feedback on the new release. I've worked extensively on the documentation and provided much more examples, as well as the new `_.each.that.allows['operator'].chaining()._`.

:-)

**Comment by kbauer** [comment]
@dwt Regarding feedback:

- Out of all fluent-iterators implementations I've tried, it feels the best overall :)
- `each` is missing some operator overloads. So far I've noticed `__contains__`, `__neg__`, `__call__`.
- For python3 it is unexpected, that `.map` etc are *not* lazy. `imap` feels like Python 2.

**Comment by javadba** [comment]
@kbauer   The non-laziness may be welcome: in general python gets fluent programming and functional programming just wrong so no need to follow python conventions in these areas. It is painful to have list(list(list( ... of nested generators.

**Comment by dwt** [comment]
@javadba Sorry, I'm not quite sure I get what you mean here?

Fluentpy generally has (or should have) all generators in imediate and lazy variants, so you can explicitly choose.

**Comment by dwt** [comment]
Strange, it seems I'm not seeing some comments here - please feel free to open a new bug if there is something I'm not seeing here.

**Comment by kbauer** [comment]
> Strange, it seems I'm not seeing some comments here - please feel free to open a new bug if there is something I'm not seeing here.

Sorry, I got embarrassed when I realized the things I was asking for (`_.each` supporting `not` and function application) are inherently impossible with the current Python API. What @javadba was referring too was that I called the existing convention (`map` is eager, a prefix `i` has to be added for lazy evaluation) feeling foreign to Python 3, which generally takes the stance that generators are the default case.

**Comment by dwt** [comment]
Ah, all clear regarding the missing comment. But yes, I would like to add as many overloads as are possible with `_.each` - so keep coming back if you find something that can be implemented.

Regarding the prefixes: I really don't know what the best way here would be. I kind of like that the default case is not lazy and I find the `I` prefix intuitive (though python2-ish). At the same time I haven't found a good prefix for a non lazy variant.

That being said - I tried at least to be internally consistent, but am of course open to suggestions.

**Comment by kbauer** [comment]
> Ah, all clear regarding the missing comment. But yes, I would like to add as many overloads as are possible with `_.each` - so keep coming back if you find something that can be implemented.

With some delay... :)

## _.each

- `__rmul__` to support `2*_.each`. Similar for other `__r...__` functions, see e.g. `_(dir(int)).filter(lambda it: it.startswith("__r")).to(list)`.
- Invoking methods on `_.each` doesn't work as expected, e.g. `_(dir(int)).filter(_.each.startswith("__r")).to(list)` doesn't filter anything out.
- The `
,$,|` operators could be overloaded as eager boolean operators (like numpy does). Though precedence rules are an issue, it would allow writing `_(range(10)).filter(  (_.each > 3) & (_.each < 7)  ).to(list)`. 

## Prefices

> Regarding the prefixes: I really don't know what the best way here would be. I kind of like that the default case is not lazy and I find the `I` prefix intuitive (though python2-ish). At the same time I haven't found a good prefix for a non lazy variant.
> 
> That being said - I tried at least to be internally consistent, but am of course open to suggestions.

"Iterator by default" can be annoying for debugging, since lazy evaluation often doesn't produce useful stack traces.
"Iterator by default" can be annoying for debugging, because it delays the failure. In

```
import fluentpy as _

def fail(value):
    assert False, "fail"

items = _(range(10)).imap(fail)

for item in items:
    print(item)
```

the line where `items` is defined doesn't appear in the backtrace while with `map` it would. So, for my personal use-cases your current choice almost always will be preferable actually.

On the other hand, making eager evaluation the default means that code written with fluentpy will be brittle. The original purpose of a function might work well with `_(...).filter`, but will suddenly fail if the passed iterable is large or infinite.

# Documentation (1)

It could be useful to point out, that the wrappers can be used as decorators to side-step the limited features of lambdas. E.g.

```
items = _(range(5))
@items.call
def items(its):
    for it in its:
        yield it
        yield it
print(items.to(list))
```

This would be yet another advantage of the suffix notation for filtering effects...

# Documentation (2)

Ad-hoc, I thought it might be useful to provide custom extensions, e.g. let's say implementing a `.groupby` that groups non-consecutive elements. Until I realized, that this is covered by `.call`. It might be worth pointing this out explicitly.

# Subprocess utility
A wrapper around `subprocess.Popen` would be useful, that allows to do something like

    lines = _(["hello","world"]).pipe(["sed", "s/l/x/g"]).to(list)

It can be done with `.call` and a function wrapping around `subprocess.Popen`; In order to prevent deadlocks, it requires multiple threads though; I had some success building a function that allowed `_(...).call(pipe(...))....` by having a thread feed the input iterator to the `Popen.stdin` and returning an iterator over `Popen.stdout`.

**Comment by dwt** [comment]
This clearly warrants discussion in a new bug report. Would you care to open one so we can focus there?

**Comment by dwt** [comment]
@kbauer I have split off the discussion into a new bug on #6 and would love for you to join me there for discussion.
